### ISSUE TITLE
Pesquisar e modelar aplicativo para acessibilidade

### ISSUE THREAD

**Issue by joellacerda** [RESTIC12/PontoCom#3]

**Comment by Levi-Soares** [comment]
Haptics, voice over e modo claro/escuro.

**Comment by Levi-Soares** [comment]
Haptics: Ação de vibrar ao clique na tela para determinadas ações tornando uma melhor interação entre usuário e app
Voice Over: Ler os botões e campos relevantes para orientar o usuário com problemas de visão 
Modo claro/escuro: Auxiliar no conforto visual dos usuários  que possuem sensibilidade/problemas na visão
